### ISSUE TITLE
sync command is too verbose

### ISSUE THREAD

**Issue by wan54** [brikis98/docker-osx-dev#103]
When running 'sync' is there a way to just display the logging and not the lines of code?

**Comment by brikis98** [comment]
Which lines of code?

**Comment by wan54** [comment]
``` bash
2015-09-07 17:26:48 [INFO] Syncing node_modules/react-tools/src/core/ReactElementValidator.js: <f+++++++
+ read message
+ do_log '\033[0;32m' '\033[0m' '2015-09-07 17:26:48' INFO 'Syncing terminal-react/node_modules/react-skylight/node_modules/reactify/node_modules/react-tools/src/core/ReactEmptyComponent.js: <f+++++++'
+ local readonly 'color=\033[0;32m'
+ shift
+ local readonly 'color_end=\033[0m'
+ shift
+ local readonly 'timestamp=2015-09-07 17:26:48'
+ shift
+ local readonly log_level=INFO
+ shift
+ local readonly 'message=Syncing terminal-react/node_modules/react-skylight/node_modules/reactify/node_modules/react-tools/src/core/ReactEmptyComponent.js: <f+++++++'
++ index_of INFO DEBUG INFO WARN ERROR INSTRUCTIONS
++ local readonly value=INFO
++ shift
++ array=("$@")
++ local readonly array
++ local i=0
++ (( i = 0 ))
++ (( i < 5 ))
++ '[' DEBUG = INFO ']'
++ (( i++  ))
++ (( i < 5 ))
++ '[' INFO = INFO ']'
++ echo 1
++ return
```

**Comment by brikis98** [comment]
Hmmm, that's something new. Not sure what's outputting that.

**Comment by wan54** [comment]
that spins the laptop's fan loud :)

**Comment by wan54** [comment]
basically for every file the lines of code are sent to the output

**Comment by brikis98** [comment]
Hm, I'm not able to repro. Are you by any chance using some sort of custom shell or rsync command?

**Comment by wan54** [comment]
was using iTerm. I'm using Terminal now. It's all good

**Comment by ain** [comment]
:+1:

**Comment by dbanck** [comment]
I'm using iTerm2 with fish as shell.

I've encountered the same problem and pinned it down to this:

``` bash
function init_docker_machine {
  log_info "Initializing docker machine $DOCKER_MACHINE_NAME"
  docker-machine start "$DOCKER_MACHINE_NAME"
  eval "$(docker-machine env $DOCKER_MACHINE_NAME)"
  configure_docker_machine
  if [[ $DOCKER_MACHINE_DRIVER_NAME == "virtualbox" ]]; then
    check_for_shared_folders
  fi
}
```

`$(docker-machine env $DOCKER_MACHINE_NAME)` will return the fish commands because `$SHELL` is fish and the output looks like this:

```
set -x DOCKER_TLS_VERIFY "1";
[...]
```

But since we're inside a bash script it will be evaluated as bash and `set -x` will force bash to ["print a trace of simple commands"](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html)

Simple fix would be to force docker-machine to output bash:

```
eval "$(docker-machine env --shell bash $DOCKER_MACHINE_NAME)"
```

**Comment by brikis98** [comment]
Why does it only happen with `docker-machine`? Would we need to do that for every `docker-machine` command?

**Comment by dbanck** [comment]
You mean why doesn't it happen with `boot2docker`? Maybe the `boot2docker init` isn't `$SHELL` aware. I don't know, I haven't used `boot2docker` since it's deprecation.

Since this is the only time we eval something from `docker-machine env` there should be no other command which needs to be changed. For me it's working well so far with only this changed.

**Comment by brikis98** [comment]
Fair enough. Would you be interested in putting together a PR with this change?
