### ISSUE TITLE
Move /Users to the /mnt/sda1 instead of /

### ISSUE THREAD

**Issue by noose** [brikis98/docker-osx-dev#109]
My project have 11k small files and iusing 1.6GB space. /Users folder is located on the / partition

``` bash
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   896.6M    112.4M    784.3M  13% /
tmpfs                   498.1M         0    498.1M   0% /dev/shm
/dev/sda1                27.8G      4.9G     21.5G  19% /mnt/sda1
cgroup                  498.1M         0    498.1M   0% /sys/fs/cgroup
/dev/sda1                27.8G      4.9G     21.5G  19% /mnt/sda1/var/lib/docker/aufs
```

but it should be located on the /mnt/sda1 (there is more space).

**Comment by brikis98** [comment]
Apologies for the delay. I missed this issue when it was filed. 

What happens when you try to use your project with docker-osx-dev? Do you get an out of disk space error?

Also, wouldn't moving to a different partition change all the file paths? If so, that would break the docker-osx-dev script. A better fix would probably be to increase the size of the `/` partition and either reduce or remove the `/mnt/sda` partition. That said, I'm not sure why boot2docker has the partitions set up this way, so if anyone knows more, please chime in.

**Comment by noose** [comment]
> Do you get an out of disk space error?

yes

>  wouldn't moving to a different partition change all the file paths

no, I just need to add symlink `rm -rf /Users; ln -s /mnt/sda1/Users /`

I moved to the docker-toolbox and increased disk size to 30GB so it's ok for me, now. :)

**Comment by brikis98** [comment]
Ah, great. Seems like a good solution others could use. Thanks for the update.
