### ISSUE TITLE
Alternative - docker-machine-nfs

### ISSUE THREAD

**Issue by intellix** [brikis98/docker-osx-dev#120]
I think this alternative is a worthy mention: https://github.com/adlogix/docker-machine-nfs
One command install and boom, file system is rapid fast now :) I never actually managed to get osx-dev working, brew didn't seem to install everything and then even after that, no luck

**Comment by peterfication** [comment]
docker-machine-nfs works perfect. But for my project it is significantly slower because a lot of files are loaded on every request in development.

I like the approach though because I can run scripts in the docker machine that generate files I need. With docker-osx-dev I have to run these scripts on my local machine and therefore need the whole environment there, too.

**Comment by rnsloan** [comment]
This is the most convenient solution I have found for a 2-way sync, but unfortunately it does not fix the file watcher problem (at least with the nodejs watcher nodemon).

**Comment by brikis98** [comment]
Thanks for suggesting the project. It's not really a bug, so I'm going to close this issue, but it may be helpful for others looking for alternatives. 

FWIW, as I explained in the README, I found build performance over NFS was too slow, and as @rnsloan mentioned, it breaks file watchers, so I still find rsync to be a better option.

**Comment by intellix** [comment]
aye, you're linking to other projects you find subpar, figured it would help someone with a quick win with a mention

**Comment by brikis98** [comment]
Feel free to submit a PR that adds it as an alternative option in the README!
