### ISSUE TITLE
Docker-compose using extends across multiple files

### ISSUE THREAD

**Issue by frodebjerke** [brikis98/docker-osx-dev#64]
In our docker-compose setup we use the [extends](https://github.com/docker/compose/blob/master/docs/extends.md) keyword to share common configuration between containers and multiple docker-compose files. This does not work with docker-osx-dev today however as it only regex' the docker-compose file.

Have I understood it right, or have I missed something obvious?

I guess using a yaml parser would be the preferred approach to support this. However I would believe ability to pass multiple docker-compose files to the `--compose-file` parameter could be a quick fix.

**Comment by brikis98** [comment]
Good catch. A yaml parser would add a fairly large dependency (so far, this project is only using shell scripts), but supporting multiple compose files makes sense. I'd gladly accept a PR for this :)

**Comment by ain** [comment]
Good catch indeed. I've just reproduced it as well. A quick hack would be to bring `volumes` out of the Compose file that is being extended, into the one extending it, so `docker-osx-dev` could catch the mount.

Definitely worth a PR, I'm using extending too.

**Comment by genezys** [comment]
One option would be to use the `docker-compose config` command. This command outputs a docker-compose configuration that is resolved across all files (extends & overrides) and normalized to version 2.

One other advantage is that volumes using local path are resolved to their full path so any volume starting with a `/` would be a local volume instead of a named volume (see #168).

**Comment by brikis98** [comment]
@genezys Great idea!

**Comment by brikis98** [comment]
Anyone interested in putting together a PR for this?

**Comment by genezys** [comment]
I currently test a patch but it completely disables the compose file argument since docker-compose config is based on compose environment variables only. 

I don't know if this is acceptable to remove this argument. Another solution would be to populate the compose environment variables with the argument, but I think there may be edge-cases with overrides and multiple files.

**Comment by brikis98** [comment]
> since docker-compose config is based on compose environment variables only

I'm not sure I understand what you mean by this?

**Comment by genezys** [comment]
I meant the command `docker-compose config` will use the compose-specific environment variables: `COMPOSE_FILE` and `COMPOSE_PROJECT_NAME` (same for all docker-compose commands). See [the Docker Compose docs](https://docs.docker.com/compose/reference/envvars/#/composeconvertwindowspaths) for more info.

You can pass `-f` and `-p` to override those but that will be unexpected by the user.

**Comment by brikis98** [comment]
Well, docker-osx-dev could be updated to take those environment variables into account. Then, based on those variables, or the `-c` flag, it can run `docker-compose config` with the proper settings.

**Comment by genezys** [comment]
I may have been a little hasty here. Of course `docker-osx-dev` could simply add the `-f` argument to any `docker-compose` call anytime the `-c` argument is used. This will override the environment but only if the argument is used, otherwise it will simply use the current environment.

**Comment by brikis98** [comment]
Sorry, I still don't quite get the issue. Perhaps if I try to phrase your argument in my own words, you can correct me where I've misunderstood:

Currently, docker-osx-dev looks for the Docker Compose configuration in one of two places:

1. The user can explicitly specify the location using the `-c` parameter.
1. If the `-c` parameter is not specified, docker-osx-dev defaults to `docker-compose.yml`. 

Once `docker-osx-dev` has the path of the Docker Compose configuration file, it reads it in and does a poor job of parsing it. As explained in this issue, the docker-osx-dev parsing logic doesn't take into account `extends`; as explained in #168, the parsing logic doesn't handle named volumes.

Your proposal is to not read the file in directly, but run `docker-compose config` to get the list of volumes instead. So now we have to think about where `docker-compose` looks for the configuration file:

1. The user can explicitly specify the location using the `-f` parameter.
1. If the `-f` parameter is not specified, `docker-compose` checks the `COMPOSE_FILE` environment variable.
1. If that environment variable is also not specified, then it defaults to `docker-compose.yml`.

The basic mismatch is that a user may provide the `-c` flag to `docker-osx-dev`, but if we just blindly run `docker-compose config`, that parameter won't be taken into account. Is that what you're trying to say?

If so, then perhaps the solution is simple: update the logic for how `docker-osx-dev`looks for the Docker Compose configuration to match that of `docker-compose` itself. That is:

1. The user can explicitly specify the location using the `-c` parameter.
1. If the `-c` parameter is not specified, check the `COMPOSE_FILE` environment variable.
1. If the environment variable is also not specified, default to `docker-compose.yml`. 

Whatever is the outcome of this process, `docker-osx-dev` can pass the configuration file path to the `docker-compose config` command using the `-f` flag and things should behave as the user expects, right?

**Comment by genezys** [comment]
Yes, my proposal was to use `docker-compose config` instead of simply reading the `docker-compose.yml` file. And I thought that it would not have a correct behavior if you override the environments with `-f`. After some tests, I was wrong.

But there is more to it that you described: multiple `docker-compose.yml` files can be combined, `docker-compose.override.yml` will automatically be combined with the default configuration. These should also be handled correctly.

I think that your solution is too complex. `docker-osx-dev` should simply call the `docker-compose` command and eventually add the `-f` argument whenever the `-c` argument is defined. This solution should cover all Docker Compose scenarios since it will let Docker Compose handle all the complexity of `docker-compose` files to produce one simple parseable output.

**Comment by brikis98** [comment]
> Yes, my proposal was to use docker-compose config instead of simply reading the docker-compose.yml file. And I thought that it would not have a correct behavior if you override the environments with -f. After some tests, I was wrong.

Ah, gotcha.

> docker-osx-dev should simply call the docker-compose command and eventually add the -f argument whenever the -c argument is defined. This solution should cover all Docker Compose scenarios since it will let Docker Compose handle all the complexity of docker-compose files to produce one simple parseable output.

Seems like a reasonable approach. Do you want to take a crack at a PR?

**Comment by genezys** [comment]
Yes, I am currently working on a patch for this one.
