### ISSUE TITLE
Rsync deleting all files created from within the container

### ISSUE THREAD

**Issue by pintomau** [brikis98/docker-osx-dev#95]
Hi,

Rsync started not being doing anything when the container creates a file.
But when I create a file locally, Rsync will delete the files created from within the container.

Log: https://gist.github.com/crybat/5f4ce748988427c245a3

**Comment by brikis98** [comment]
What is in your `/Users/mauropinto/data` folder on your local system? Was there something different in the same folder on the VM image?

**Comment by pintomau** [comment]
Yes there were some files in the data folder.
When I change/create them locally rsync picks them up, but deletes the files created by the container.
If I create files in the container, rsync doesn't react.

**Comment by brikis98** [comment]
Ah. rsync is a **one way** sync. That means it will only pick up changes on your host computer (OS X) and sync them to the docker VM. It will not sync the other way around. There is no fix for that unless we change over to a different technology than rsync (e.g. unison). See #90.  

Moreover, because we've enabled the delete flags, rsync will delete any files on the VM that are not on your host (this way, when you delete something on the host, files stay in sync). If the container is generating files during runtime that should not be deleted, you should add them to the ignore list via  command line flags (run `docker-osx-dev -h` to see all supported flags).

**Comment by pintomau** [comment]
I would swear I saw it doing both ways before. Oh well.
I'm trying CoreOS in Virtualbox with nfs and it's working well for me atm.
Not perfect though; would prefer working with docker locally.

Thanks.
